[project]
name = "AI_Agent_Travel_Planner"
version = "0.1.0"
dependencies = [
    "langgraph",
    "langchain-openai",
    "python-dotenv",
    "openai",
    "requests",
    "playwright",
    "nest-asyncio",
    "tqdm",
]

[tool.setuptools]
py-modules = ["main", "state"]
packages = ["nodes", "utils"]
